language: python
python:
  - "2.6"
  - "2.7"
before_install:
  # install numpy non-python dependencies
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran
  - mkdir builds
  - pushd builds
  # install build dependencies
  - travis_retry pip install -q tornado jinja2 GitPython
  # install cython
  - travis_retry pip install --install-option="--no-cython-compile" Cython
  # install numpy
  - travis_retry pip install -q numpy==1.9.1
  # install scipy
  - travis_wait pip install -q scipy==0.13
  # install matplotlib
  - travis_retry pip install -q matplotlib==1.3.1
  # install astropy
  - travis_retry pip install -q astropy==1.0
  # install GLUE
  - travis_retry pip install -q --egg https://www.lsc-group.phys.uwm.edu/daswg/download/software/source/glue-1.46.tar.gz#egg=glue-1.46
  - popd
install:
  - pip install -q .
script:
  - python setup.py test
