language: python
python:
  - "2.6"
  - "2.7"
  - "2.7_with_system_site_packages"
before_install:
  - mkdir builds
  - pushd builds
  # install numpy non-python dependencies
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran
  # add LSCSoft sources
  - echo "deb http://software.ligo.org/lscsoft/debian wheezy contrib" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get --assume-yes --allow-unauthenticated install lscsoft-archive-keyring
  - sudo apt-get update -qq
  - sudo apt-get --assume-yes install libhdf5-dev lal-python lalframe-python ldas-tools-framecpp-python
  - sudo apt-get --assume-yes install krb5-user python-nds2-client
  # install build dependencies
  - travis_retry pip install -q tornado jinja2 GitPython
  # install cython
  - travis_retry pip install --install-option="--no-cython-compile" Cython
  # install python dependencies
  - travis_retry pip install -q numpy==1.9.1
  - travis_wait pip install -q scipy==0.16
  - travis_retry pip install -q matplotlib==1.3.1
  - travis_retry pip install -q astropy==1.0
  - travis_retry pip install -q h5py
  - travis_retry pip install -q unittest2
  - travis_retry pip install -q importlib
  - travis_retry pip install -q pytest
  - travis_retry pip install -q coveralls
  # install LSCSoft python packages
  - travis_retry pip install -q kerberos
  - travis_retry pip install -q cjson
  - travis_retry pip install -q M2Crypto
  - travis_retry pip install -q --egg http://software.ligo.org/lscsoft/source/glue-1.49.1.tar.gz#egg=glue-1.49.1
  - travis_retry pip install -q --egg http://software.ligo.org/lscsoft/source/dqsegdb-1.2.2.tar.gz#egg=dqsegdb-1.2.2
  - popd
install:
  - python setup.py build
script:
  - coverage run --source=gwpy --omit="gwpy/tests/*,gwpy/*version*,gwpy/utils/sphinx/*" -m py.test -v
  - pip install .
after_success:
  - coveralls
notifications:
  slack:
    secure: jQdoSpwNbUnq0Eo7o6Ko7vuhu58LQdfy8jFKxLUnUjv/GLezK/PPAQCU9SgmyDPh1yD8sb5Xa8UtbNfGtpYdwBAGwZxPHz3oQQAflivFwcF6UP7/NlAB9muSOOnL0QfQyX1I4sIKOkX+gkl+TBciX4v58B8NUU02dDkwDqTLUqQ=
