language: python
python:
  - "2.6"
  - "2.7"
before_install:
  # install numpy non-python dependencies
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran
  - mkdir builds
  - pushd builds
  # install cython
  - travis_retry pip install --install-option="--no-cython-compile" Cython
  # install numpy
  - travis_retry pip install numpy
  # install scipy
  - travis_retry pip install -vvv scipy
  # install matplotlib
  - travis_retry pip install matplotlib>=1.3.1
  # install astropy
  - travis_retry pip install astropy>=0.4
  # install GLUE
  - travis_retry pip install --egg https://www.lsc-group.phys.uwm.edu/daswg/download/software/source/glue-1.46.tar.gz#egg=glue-1.4
  - popd
install:
  - pip install .
script:
  - python setup.py test
