language: python
python:
  - "2.6"
  - "2.7"
before_install:
  # install numpy non-python dependencies
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran
  - mkdir builds
  - pushd builds
  # install cython
  - pip install --install-option="--no-cython-compile" Cython
  # install GLUE
  - pip install -q --egg https://www.lsc-group.phys.uwm.edu/daswg/download/software/source/glue-1.46.tar.gz#egg=glue-1.4
  - popd
install:
  - pip install .
script:
  - python setup.py test
